# saner window splits 
bind | split-window -h
bind - split-window -v

# shortcut to reload tmux
bind R source-file ~/.tmux.conf \; display "~/.tmux.conf reloaded"

# vim movements ftw!
bind k select-pane -U
bind j select-pane -D
bind h select-pane -L
bind l select-pane -R

# automatically set window titles
set-window-option -g automatic-rename on
set-option -g set-titles on

# synchronize panes - send the same command to all panes
bind E setw synchronize-panes

# enable mouse interaction 
setw -g mouse on

# use vim movement for copy paste
setw -g mode-keys vi

# color go brrr
set -g default-terminal "screen-256color"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
